### ISSUE TITLE
Intel SGX

### ISSUE THREAD

**Issue by imacoindev** [EspeoBlockchain/gardener-server#21]
Integrate Intel SGX to prove data validity.

**Comment by ksamborski** [comment]
I've done some research about possible solutions and these are my findings.

## What is Intel SGX?

Intel Software Guard Extensions is a set of new CPU instructions that
allows to program some part of the application in a secure place in memory
called enclave.

That place is encrypted and cannot be accessed from outside the enclave
regardless of the current privilege level and CPU mode. What does it mean?
Normally when you run a program you can attach a debugger process to see its
memory or to disassemble it. Moreover programs with special privileges like
operating system can inspect or even alter it. Enclaves are resistant to such
actions.

What's more important enclaves can generate a report that can be used to proof
that the code was run in it. Intel has also released a service which can verify
that the report generated by enclave comes from genuine Intel processor
with enabled SGX.

## Limitations of enclaves

As we can read in a few places, such as:

- https://download.01.org/intel-sgx/linux-2.5/docs/Intel_SGX_Developer_Guide.pdf
- https://software.intel.com/en-us/articles/intel-software-guard-extensions-tutorial-part-1-foundation
- http://www.tatetian.io/2016/01/25/file-io-inside-intel-sgx-enclave/

enclaves have some limitations, like:

- they cannot make any OS calls (e.g. reading/writing files, networking, HTTP calls etc.)
- they cannot be debugged by software or hardware debuggers
- the protected memory, set by the system BIOS cannot typically exceed 64 MB
- their code must be written in C/C++

Keeping that in mind it's also advisable to keep them as small as possible.

## SGX and blockchain oracles

Oracles have a problem of trust. How user can know that it's not doing
something malicious or even nothing and just spending the user's money (gas)?
One thing that can help is to opensource the oracle so anyone can verify it.
But then someone may still ask if the running process of oracle hasn't been
compromised, for example it's memory might been altered. And that's the case
for enclaves.

Such solution already exists and it's described very well in this document:
https://eprint.iacr.org/2016/168.pdf

Town Crier (TC) oracle consists of 3 components:
- smart contract
- relay
- enclave

TC smart contract can be called by any user's contract and initiates any oracle
work by sending events. It also verifies if oracle responses with result made
from its request.

Relay listen to that events and works like simple broker between enclave and outer world.
For example if enclave needs some data from any REST service it asks relay to
do it. Also when enclave finishes its work then relay passes the result to TC
smart contract.

## Node.js and SGX

There are two ways to make use of enclaves in current code. Node has [Addon API](https://nodejs.org/api/addons.html)
which can be used to run C++ code from Javascript. First would be to write all
enclave code in C++ as an addon and call it normally like any function from JS.

There is also other way. Some people created
[node-secureworker](https://github.com/luckychain/node-secureworker) which
comes as an Node addon and allows to write enclave code in JS. Of course it has
the same limitations like any other enclave code such as lack of I/O so we
still cannot make any HTTP calls from it.

It makes use of [Duktape](http://duktape.org/) which is a very small JS engine
that can be embedded in enclave. Thus any JS code we pass will be executed by
it in secured environment. It has also some additional limitations:

- Duktape has only partial support for ES6 and ES7
- implementation of node-secureworker is not complete and it doesn't seem to be
actively developed

**Comment by kss-espeo** [comment]
Further research:

Since REST requests can't be made from within an enclave, it is necessary for a trusted party (gardener-server) to provide response body and send it using some safe method. This method is called [Remote attestation](https://courses.cs.ut.ee/MTAT.07.022/2017_spring/uploads/Main/hiie-report-s16-17.pdf)

After verifying data, SGX will produce hash for enclave bytecode. Gardener caller should be able to retrieve it and confirm that it indeed has been ran within an SGX enclave using publicly available Intel Attestation Service.

**Comment by kss-espeo** [comment]
It's blocked because Intel Attestation Service returns 400 when calling it: https://github.com/intel/sgx-ra-sample/issues/28

**Comment by kss-espeo** [comment]
This is finished - meaning we have Intel SGX, along with Remote Attestation integrated. There is more potential of utilising SGX features, but this will be done in other tasks.
