### ISSUE TITLE
Custom errors are not correctly handled

### ISSUE THREAD

**Issue by kss-espeo** [EspeoBlockchain/gardener-server#24]
1. Call oracle with a malformed URL, for example `UsingOracle.deployed().then(instance => instance.request("json(badUrl"))`
2. Wait for a transaction to be mined

Expected: A stacktrace of InvalidUrlError is found in the logs
Expected: 1000 error code is being logged
Actual: No error logging at all
Actual: No error code is logged: `Created response [response={"requestId":"0x3b7602292b26ffa4b1bea411d4594bcbd24a9b288169cd3f739c88a19c604cf4","state":{"name":"Processed"},"errorCode":0}]`

This is just an example, such a case is also true for other custom errors, namely HttpError and InvalidContentTypeError.

**Comment by starspire** [comment]
@kss-espeo check if #26 fixed it. If so, please close this issue. But it seems that this issue is about incorrect logs in server rather than handling errors wrongly. Please investigate it.

**Comment by kss-espeo** [comment]
After all, it turned out that errors were handled correctly. They were however not correctly logged - which was improved.
