### ISSUE TITLE
Send descriptive error message along with error code to gardener-monitor

### ISSUE THREAD

**Issue by kss-espeo** [EspeoBlockchain/gardener-server#30]
Because gardener-monitor will be used for demos and error code won't mean anything to anyone but Gardener devs.

**Comment by kss-espeo** [comment]
This is actually going to be done on gardener-monitor side. We will keep errocCode->message mapping there which is unfortunate since this is duplicate of information stored in gardener-server. We will still however going to go for it, because alternative would require modifying gardener-smart-contracts which I'd prefer to avoid.

**Comment by starspire** [comment]
This approach is targeted, because of the transaction fee. Sending number is much cheaper than a string with an error message. Moreover, it's a language agnostic.
