### ISSUE TITLE
Divide source code and test code

### ISSUE THREAD

**Issue by kss-espeo** [EspeoBlockchain/gardener-server#37]
Currently our test files live next to source files. This leads to some awkwardness like:

- inability to configure app and test environment distinctly
- in some cases, app source, test source and test data living in same package (yikes!)
- reducing code readibility

Objectives of this tasks are:

- Move all test sources - `*.spec.ts` and `*.integration.ts` to a location separate from source code. Look up what are TS standards for this, but my idea is a "Java-like" approach with src/ root for source code and test/ root for test stuff.
- Provide a distinct configuration (`tsconfig.json`) for app and tests. Test config and app config will likely derive from some root config (use "extends" keyword)

**Comment by starspire** [comment]
After group discussion we decided to keep tests files where they currently are, but move all test data files to separate folder called `testdata` or similar and add in `tsconfig.js` path `@testdata` path for it.
