### ISSUE TITLE
Gardener demo

### ISSUE THREAD

**Issue by imacoindev** [EspeoBlockchain/gardener-server#39]
We could create a web app that demonstrates what Gardener can do to new users and developers. This is what I suggest as a high level overview of the app:

- Persistent: The app is online all the time and can be accessed via browser.
- Allows the user to request data by sending a request to a deployed Gardener smart contract and returns the result of the request to the browser to be seen by the user. It is a live demo of what a Gardener instance can do.
- It demonstrates different data sources. For example, allows to select what type of data the user wants (random, url, etc). The amount of data sources can be increased as we integrate more to the server.
- It demonstrates different proofs that can be used to verify the validity of data. For example, user can choose to use IntelSGX or NotaryTLS to verify a data source. 
- The on-chain contents are deployed in Ethereum testnet. Our requests are visible in the testnet for anyone to verify that they are actually executed on-chain.

Similar type of demo has been done by Provable: http://app.provable.xyz/home/test_query

Some user stories(all features are not ready, but we should be able to add them to the app later):
- As a user I can have a simple demonstration of obtaining data using Gardener.
- As a user I can select different data sources
- As a user I can select different proofs to validate the data that is delivered is not tampered with. 
- As a user I can see that the style and design of the site matches that of https://gardeneroracle.io/
- The demo can be accessed through demo.gardeneroracle.io

**Comment by lmazurowski** [comment]
According to the sentence:

> Allows the user to request data by sending a request to a deployed Gardener smart contract and returns the result of the request to the browser to be seen by the user. It is a live demo of what a Gardener instance can do.

I think we should prepare separate app for this, since Monitor is an optional web app just for showing requests into taken from server.

We can prepare monorepo (for example with [lerna](https://github.com/lerna/lerna)) for the Monitor AND (lets name it - the Console) to provide more modularity and not to change behaviour of the Monitor. 

In this way we can just add another module to the current architecture.

**Comment by kss-espeo** [comment]
> I think we should prepare separate app for this, since Monitor is an optional web app just for showing requests taken from the Gardener Server via WS.
Agreed.

> There will be of course some work with the REST Api on the server side, since we must support queries from the Console.
I believe we could try to leverage some web plugin that allows interactions with Smart Contracts via a browser. https://metamask.io/ comes to mind. That way there is no need to add code to Gardener, and instead we can just interact with a Gardener instance that is deployed on a test Ethereum network. Still, we need to get output from monitor so maybe some REST interface will be needed. This needs some careful consideration though, as it introduces a potential security risk.

> In this way we can just add another module to the current architecture.

If possible, I'd prefer to keep such app completely distinct from Gardener stack. If we really need to couple Gardener and that `Console` app, then I'd like to keep that coupling to a minimum. Then again, the more we talk about it the more I think we need @starspire eyes on it before making decisions ;)

**Comment by starspire** [comment]
Guys, how about integrating console into Gardener Monitor as a single repo? We can utilize Metamask to get given user account and moreover we do not need implement any REST interface as Monitor operates directly on blockchain and any query request also should be performed the same way (direct blockchain communication).
